[package]
name = "cactus-ingest"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
strum_macros = "0.27.2"
log = "0.4.28"
cactus-foundation = { path = "../cactus-foundation" }