name: Cactus Runtime | Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MANIFEST_PATH: cactus-runtime/Cargo.toml

jobs:
  cactus_build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --manifest-path $MANIFEST_PATH --verbose
    - name: Run tests
      run: cargo test --manifest-path $MANIFEST_PATH --verbose
